
insert into PRODUCTENTITY ( name, price,image) values ('Pinturas de iris',500, 'http://www.creadictos.com/wp-content/uploads/2015/08/vibrantes-pinturas-iris-scott-07.jpg');
insert into PRODUCTENTITY ( name, price,image) values ('Lobo',500, 'https://s-media-cache-ak0.pinimg.com/736x/91/02/46/910246740d93cf759e067802bccc5e7f--bored-panda-art-design.jpg');
insert into PRODUCTENTITY ( name, price,image) values ('Tankekart',500, 'https://upload.wikimedia.org/wikipedia/commons/0/09/Pintura-oleo.jpg');
insert into PRODUCTENTITY ( name, price,image) values ('Loro',500, 'http://marcianosmx.com/wp-content/uploads/2015/10/Hua-Tunan-pinturas-murales-7.jpg');
insert into PRODUCTENTITY ( name, price,image) values ('Pintura nostalgica',500, 'https://s-media-cache-ak0.pinimg.com/736x/98/42/b0/9842b072a467a7a038cf5f2a746b8133--colorful-paintings-paintings-on-canvas.jpg');
insert into PRODUCTENTITY ( name, price,image) values ('Violonchelo',500, 'http://3.bp.blogspot.com/--Nib8Myf3M8/VQDpdM8Ww_I/AAAAAAADDgU/cHoCDWxDMT8/s1600/pinturas-modernas-al-oleo%2Bpor-leonid-afremov%2B(10).jpg');
insert into PRODUCTENTITY ( name, price,image) values ('Tigre',500, 'http://3.bp.blogspot.com/-Fg4p2uoBl6E/VQDpdPYaXgI/AAAAAAADDgY/BhwOGII5jG8/s1600/pinturas-modernas-al-oleo%2Bpor-leonid-afremov%2B(11).jpg');
insert into PRODUCTENTITY ( name, price,image) values ('Tormenta',500, 'https://roc21cdn-roc21.netdna-ssl.com/blog/wp-content/uploads/2016/06/pinturas-sobre-agua.jpg');
insert into PRODUCTENTITY ( name, price,image) values ('Oleo',500, 'https://s-media-cache-ak0.pinimg.com/736x/22/fa/d8/22fad8158087784046bde52071637365--irises-umbrellas.jpg');
insert into PRODUCTENTITY ( name, price,image) values ('Venecia',500, 'http://1.bp.blogspot.com/-mpjjw-s3kVM/VQDphfcKWMI/AAAAAAADDhU/tRN6unv94oY/s1600/pinturas-modernas-al-oleo%2Bpor-leonid-afremov%2B(7).jpg');
insert into PRODUCTENTITY ( name, price,image) values ('Ojo',500, 'http://1.bp.blogspot.com/-xtMv25aY8sQ/UdF1x76QRcI/AAAAAAACuWA/_t4-pOWD-gk/s550/Michael+Creese+-+Tutt%27Art@+(2).jpg');
insert into PRODUCTENTITY ( name, price,image) values ('Bailarina',500, 'http://1.bp.blogspot.com/-ElpPLkecM0o/VQDphxTQ_mI/AAAAAAADDhc/hChLNLER92c/s1600/pinturas-modernas-al-oleo%2Bpor-leonid-afremov%2B(9).jpg');
insert into PRODUCTENTITY ( name, price,image) values ('Horror',500, 'http://static.vix.com/es/sites/default/files/styles/large/public/btg/curiosidades.batanga.com/files/5-famosas-pinturas-que-fueron-robadas.jpg?itok=HpeL9Vf0');
insert into PRODUCTENTITY ( name, price,image) values ('Callejon',500, 'http://www.creadictos.com/wp-content/uploads/2015/08/vibrantes-pinturas-iris-scott-05.jpg');
insert into PRODUCTENTITY ( name, price,image) values ('Ciudad',500, 'http://www.pinturayartistas.com/wordpress/wp-content/uploads/2013/01/the_melody_of_the_night_by_leonidafremov.jpg');
insert into PRODUCTENTITY ( name, price,image) values ('Rio',500, 'http://i0.wp.com/artefeed.com/wp-content/uploads/2015/02/Bellas-pinturas-de-paisajes-de-Graham-Gercken-5.jpg');
insert into PRODUCTENTITY ( name, price,image) values ('Rostro',500, 'http://lamanufacturera.com/wp-content/uploads/2012/11/WALKER-2.jpg');
insert into PRODUCTENTITY ( name, price,image) values ('Monalisa',500, 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/220px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg');
insert into PRODUCTENTITY ( name, price,image) values ('Violinista',500, 'https://s-media-cache-ak0.pinimg.com/736x/89/ff/27/89ff2746c3e2ba92ff71cd674e110abd--painting-canvas-abstract-paintings.jpg');
insert into PRODUCTENTITY ( name, price,image) values ('Lluvia',500, 'http://www.creadictos.com/wp-content/uploads/2015/08/vibrantes-pinturas-iris-scott-04.jpg');
insert into PRODUCTENTITY ( name, price,image) values ('Parque',500, 'http://1.bp.blogspot.com/-mlemAGqFZiI/VQDpdNjBs3I/AAAAAAADDgc/P556S-9gFPw/s1600/pinturas-modernas-al-oleo%2Bpor-leonid-afremov%2B(2).jpg');
insert into PRODUCTENTITY ( name, price,image) values ('Japon',500, 'https://http2.mlstatic.com/autumn-in-the-big-city-cuadros-pinturas-de-dmitry-spiros-D_NQ_NP_11906-MLM20051815754_022014-F.jpg');
insert into PRODUCTENTITY ( name, price,image) values ('Lectora',500, 'https://i1.wp.com/artefeed.com/wp-content/uploads/2015/05/ivan-alifan-pinturas-14.jpg');
insert into PRODUCTENTITY ( name, price,image) values ('Ballet',500, 'https://ae01.alicdn.com/kf/HTB1dW4pIXXXXXXAXFXXq6xXFXXXx/Imagen-Moderna-Pinturas-Bailar-n-de-Ballet-Pintura-Al-leo-Pintado-A-Mano-Sobre-Lienzo-Paisaje.jpg');


INSERT INTO CATEGORYENTITY(name) values('Grafico');
INSERT INTO CATEGORYENTITY(name, parentcategory_id) values('Fotorealismo',1);
INSERT INTO CATEGORYENTITY(name, parentcategory_id) values('Anamorfosis',1);
INSERT INTO CATEGORYENTITY(name, parentcategory_id) values('Graffiti ecologico',1);
INSERT INTO CATEGORYENTITY(name) values('Barroco');
INSERT INTO CATEGORYENTITY(name, parentcategory_id) values('Paisajes',5);
INSERT INTO CATEGORYENTITY(name, parentcategory_id) values('Retratos',5);
INSERT INTO CATEGORYENTITY(name, parentcategory_id) values('Vanitas',5);
INSERT INTO CATEGORYENTITY(name) values('Latino');
INSERT INTO CATEGORYENTITY(name, parentcategory_id) values('Academicismo',9);
INSERT INTO CATEGORYENTITY(name, parentcategory_id) values('Argentina',9);
INSERT INTO CATEGORYENTITY(name, parentcategory_id) values('Peru',9);
INSERT INTO CATEGORYENTITY(name) values('Europeo');
INSERT INTO CATEGORYENTITY(name, parentcategory_id) values('Renacimiento',13);
INSERT INTO CATEGORYENTITY(name, parentcategory_id) values('Manierismo',13);
INSERT INTO CATEGORYENTITY(name, parentcategory_id) values('Neoclasisismo',13);

insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (1, 2);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (2, 2);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (3, 2);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (4, 2);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (5, 2);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (6, 2);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (1, 3);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (2, 3);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (3, 3);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (4, 3);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (5, 3);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (6, 3);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (1, 4);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (2, 4);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (3, 4);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (4, 4);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (5, 4);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (6, 4);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (7, 6);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (8, 6);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (9, 6);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (10, 6);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (11, 6);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (12, 6);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (7, 7);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (8, 7);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (9, 7);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (10, 7);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (11, 7);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (12, 7);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (7, 8);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (8, 8);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (9, 8);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (10, 8);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (11, 8);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (12, 8);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (13, 10);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (14, 10);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (15, 10);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (16, 10);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (17, 10);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (18, 10);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (13, 11);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (14, 11);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (15, 11);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (16, 11);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (17, 11);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (18, 11);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (13, 12);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (14, 12);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (15, 12);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (16, 12);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (17, 12);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (18, 12);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (19, 14);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (20, 14);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (21, 14);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (22, 14);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (23, 14);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (24, 14);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (19, 15);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (20, 15);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (21, 15);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (22, 15);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (23, 15);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (24, 15);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (19, 16);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (20, 16);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (21, 16);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (22, 16);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (23, 16);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (24, 16);

