
insert into PRODUCTENTITY ( name, price,image) values ('Gigante',500, 'https://giantcdn-qu2qwwv2de7wv85rz.stackpathdns.com/remote/www.giant-bicycles.com/_upload_mx/bikes/models/xxl/Propel-ADV-1_plus_Comp_Red.jpg?width=1028&height=685&mode=pad&bgcolor=white&anchor=middlecenter');
insert into PRODUCTENTITY ( name, price,image) values ('Gigante2',500, 'https://giantcdn-qu2qwwv2de7wv85rz.stackpathdns.com/remote/www.giant-bicycles.com/_upload_mx/bikes/models/xxl/TCR%20ADV%202_Blue.jpg?width=1028&height=685&mode=pad&bgcolor=white&anchor=middlecenter');
insert into PRODUCTENTITY ( name, price,image) values ('Huffy',500, 'http://media.aws.alkosto.com/media/catalog/product/cache/6/small_image/280x/4275c8e8146210f1c7867d9f605120ed/2/8/28914226350_3_.jpg');
insert into PRODUCTENTITY ( name, price,image) values ('Benotto',500, 'http://tienda.benotto.com/images/usrGallery/Imagenes/Benotto/catBicicletas.jpg');
insert into PRODUCTENTITY ( name, price,image) values ('Wheels',500, 'http://static.websguru.com.ar/var/m_9/92/92e/38838/648475-fat_bike.jpg');
insert into PRODUCTENTITY ( name, price,image) values ('Carrera',500, 'http://stlbikes.com/wp-content/uploads/2014/10/miniatura-BicicletaUrbanaFixed-570x444.jpg');
insert into PRODUCTENTITY ( name, price,image) values ('Collection',500, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0j4R77STBDBuI-KkL7HHox_KeEIptt1cRdQAF1USo6WGS1YNm');
insert into PRODUCTENTITY ( name, price,image) values ('Montana',500, 'https://www.todomountainbike.net/images/articles/2016/bicicletas-electricas-mtb-bikelec-1.jpg');
insert into PRODUCTENTITY ( name, price,image) values ('Venzo',500, 'https://http2.mlstatic.com/bicicletas-venzo-vulcan-rin-29-shimano-deore-freno-hidraulic-D_NQ_NP_208411-MCO20552812236_012016-F.jpg');
insert into PRODUCTENTITY ( name, price,image) values ('Tour',500, 'https://www.clootbike.com/images/products/comprar-bicicletas-de-carretera-madrid.jpg');
insert into PRODUCTENTITY ( name, price,image) values ('Bicicletas',500, 'http://corona.vteximg.com.br/arquivos/bicicleta.jpg');
insert into PRODUCTENTITY ( name, price,image) values ('Amortiguador',500, 'https://giantcdn-qu2qwwv2de7wv85rz.stackpathdns.com/remote/www.giant-bicycles.com/_upload_mx/bikes/models/xxl/Trance%202_Yellow.jpg?width=1028&height=685&mode=pad&bgcolor=white&anchor=middlecenter');
insert into PRODUCTENTITY ( name, price,image) values ('Special radio',500, 'https://www.megatone.net/Images/Articulos/zoom2x/BIC1200KAW.jpg');
insert into PRODUCTENTITY ( name, price,image) values ('Kids',500, 'http://homecenterco.scene7.com/is/image/SodimacCO/cat940041?$Redesing223$');
insert into PRODUCTENTITY ( name, price,image) values ('Big fork',500, 'https://dfp2hfrf3mn0u.cloudfront.net/144/144086_original_1.jpg');
insert into PRODUCTENTITY ( name, price,image) values ('Speedo',500, 'https://http2.mlstatic.com/bicicletas-drive-fixie-rin-26-llantas-700cc-silla-ergonomico-D_NQ_NP_294011-MCO20449443497_102015-F.jpg');
insert into PRODUCTENTITY ( name, price,image) values ('Fucsia',500, 'http://kefixie.com/37/bicicleta-fixie-origin-8-fix8-negra-y-rosa.jpg');
insert into PRODUCTENTITY ( name, price,image) values ('Bateria',500, 'https://media.aws.alkosto.com/media/catalog/product/cache/3/image/8bf9d84cc5f65bd89f2d4160406987fb/v/i/viaggo_lateral_izquierda_640x390-01_1.png');
insert into PRODUCTENTITY ( name, price,image) values ('Ciudad',500, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCxPZdLgZIhi1X7PuhpVE3zOVwlIynIazkUcyzW3AmXp0n1K1vVQ');
insert into PRODUCTENTITY ( name, price,image) values ('Cartoon',500, 'http://jumbocolombia.vteximg.com.br/arquivos/ids/191939-1000-1000/JU280-12101-4LPS-7453008190625-PAW-PATROL-BICICLETA-12.jpg');
insert into PRODUCTENTITY ( name, price,image) values ('Fancy',500, 'https://www.bicicletaselectricas.info/wp-content/uploads/2016/06/Bicicletas-electricas-que-se-recargan-pedaleando.jpg');
insert into PRODUCTENTITY ( name, price,image) values ('Champion',500, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCxPZdLgZIhi1X7PuhpVE3zOVwlIynIazkUcyzW3AmXp0n1K1vVQ');
insert into PRODUCTENTITY ( name, price,image) values ('Naranja',500, 'https://sgfm.elcorteingles.es/SGFM/dctm/MEDIA03/201702/16/00108452763314____1__640x640.jpg');
insert into PRODUCTENTITY ( name, price,image) values ('Montan bike',500, 'http://www.habicicletas.com/images/stories/habicicletas/noticias/frank-osorio-noticias-ha-bicicletas.jpg');


INSERT INTO CATEGORYENTITY(name) values('Terreno');
INSERT INTO CATEGORYENTITY(name, parentcategory_id) values('pro',1);
INSERT INTO CATEGORYENTITY(name, parentcategory_id) values('amateur',1);
INSERT INTO CATEGORYENTITY(name, parentcategory_id) values('cahmpionship',1);
INSERT INTO CATEGORYENTITY(name) values('Ciudad');
INSERT INTO CATEGORYENTITY(name, parentcategory_id) values('Bateria',5);
INSERT INTO CATEGORYENTITY(name, parentcategory_id) values('Femenina',5);
INSERT INTO CATEGORYENTITY(name, parentcategory_id) values('Sport',5);
INSERT INTO CATEGORYENTITY(name) values('Pista');
INSERT INTO CATEGORYENTITY(name, parentcategory_id) values('Carreras',9);
INSERT INTO CATEGORYENTITY(name, parentcategory_id) values('Tour',9);
INSERT INTO CATEGORYENTITY(name, parentcategory_id) values('Rally',9);
INSERT INTO CATEGORYENTITY(name) values('Infantiles');
INSERT INTO CATEGORYENTITY(name, parentcategory_id) values('Cartoon',13);
INSERT INTO CATEGORYENTITY(name, parentcategory_id) values('Asistida',13);
INSERT INTO CATEGORYENTITY(name, parentcategory_id) values('Colores',13);

insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (1, 2);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (2, 2);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (3, 2);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (4, 2);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (5, 2);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (6, 2);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (1, 3);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (2, 3);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (3, 3);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (4, 3);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (5, 3);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (6, 3);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (1, 4);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (2, 4);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (3, 4);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (4, 4);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (5, 4);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (6, 4);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (7, 6);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (8, 6);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (9, 6);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (10, 6);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (11, 6);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (12, 6);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (7, 7);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (8, 7);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (9, 7);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (10, 7);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (11, 7);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (12, 7);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (7, 8);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (8, 8);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (9, 8);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (10, 8);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (11, 8);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (12, 8);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (13, 10);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (14, 10);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (15, 10);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (16, 10);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (17, 10);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (18, 10);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (13, 11);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (14, 11);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (15, 11);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (16, 11);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (17, 11);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (18, 11);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (13, 12);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (14, 12);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (15, 12);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (16, 12);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (17, 12);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (18, 12);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (19, 14);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (20, 14);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (21, 14);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (22, 14);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (23, 14);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (24, 14);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (19, 15);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (20, 15);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (21, 15);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (22, 15);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (23, 15);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (24, 15);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (19, 16);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (20, 16);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (21, 16);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (22, 16);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (23, 16);
insert into PRODUCTENTITY_CATEGORYENTITY (productentity_id, category_id) values (24, 16);


